import AppLayout from "@/components/layout/AppLayout";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { FileText, CheckCircle, XCircle, AlertTriangle, Scale, Ban, Shield, RefreshCw } from "lucide-react";

const Terms = () => {
  const sections = [
    {
      icon: CheckCircle,
      title: "Acceptance of Terms",
      content: [
        {
          subtitle: "Agreement to Terms",
          text: "By accessing or using AI Solutions' services, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using or accessing our services."
        },
        {
          subtitle: "Modifications",
          text: "We reserve the right to modify these terms at any time. We will provide notice of material changes through email or service notifications. Your continued use of the services after such modifications constitutes acceptance of the updated terms."
        },
        {
          subtitle: "Eligibility",
          text: "You must be at least 18 years old and have the legal capacity to enter into contracts to use our services. By using our services, you represent and warrant that you meet these requirements."
        }
      ]
    },
    {
      icon: Shield,
      title: "Use of Services",
      content: [
        {
          subtitle: "License Grant",
          text: "Subject to these terms, we grant you a limited, non-exclusive, non-transferable, revocable license to access and use our AI solutions for your internal business purposes in accordance with your subscription plan."
        },
        {
          subtitle: "Account Responsibilities",
          text: "You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must immediately notify us of any unauthorized use of your account."
        },
        {
          subtitle: "Acceptable Use",
          text: "You agree to use our services only for lawful purposes and in accordance with these terms. You must not use our services in any way that violates applicable laws or regulations, infringes third-party rights, or could damage our systems or reputation."
        },
        {
          subtitle: "Data Input",
          text: "You are solely responsible for the content, accuracy, and legality of any data you input into our AI solutions. You warrant that you have all necessary rights and permissions to use such data with our services."
        }
      ]
    },
    {
      icon: Ban,
      title: "Prohibited Activities",
      content: [
        {
          subtitle: "System Interference",
          text: "You must not attempt to interfere with, compromise, or disrupt the integrity or performance of our services, networks, or data. This includes introducing viruses, malware, or any harmful code."
        },
        {
          subtitle: "Unauthorized Access",
          text: "You must not attempt to gain unauthorized access to any portion of our services, systems, networks, or data through hacking, password mining, or any other means."
        },
        {
          subtitle: "Misuse of AI",
          text: "You must not use our AI solutions to generate illegal content, spread misinformation, infringe intellectual property rights, or engage in any activity that could harm individuals or organizations."
        },
        {
          subtitle: "Competitive Analysis",
          text: "You must not use our services to build competitive products or services, conduct benchmarking without written permission, or reverse engineer our technology."
        }
      ]
    },
    {
      icon: Scale,
      title: "Intellectual Property",
      content: [
        {
          subtitle: "Our Rights",
          text: "All intellectual property rights in our services, including software, algorithms, designs, trademarks, and documentation, are owned by AI Solutions or our licensors. These terms do not grant you any ownership rights to our intellectual property."
        },
        {
          subtitle: "Your Content",
          text: "You retain all ownership rights to the content and data you input into our services. By using our services, you grant us a limited license to process your content solely to provide and improve our services."
        },
        {
          subtitle: "AI-Generated Output",
          text: "Subject to these terms and your subscription, you own the output generated by our AI solutions based on your inputs. However, we retain the right to use aggregated, anonymized output data to improve our services."
        },
        {
          subtitle: "Feedback",
          text: "Any feedback, suggestions, or ideas you provide about our services become our property, and we may use them without obligation or compensation to you."
        }
      ]
    },
    {
      icon: AlertTriangle,
      title: "Disclaimers & Limitations",
      content: [
        {
          subtitle: "Service Availability",
          text: "Our services are provided 'as is' and 'as available' without warranties of any kind. We do not guarantee that our services will be uninterrupted, error-free, or completely secure, though we strive for high availability and security."
        },
        {
          subtitle: "AI Accuracy",
          text: "While our AI solutions are designed to be accurate and helpful, we do not warrant that AI-generated outputs will be error-free, complete, or suitable for your specific purposes. You should review and verify all AI outputs before relying on them for critical decisions."
        },
        {
          subtitle: "Limitation of Liability",
          text: "To the maximum extent permitted by law, AI Solutions shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly."
        },
        {
          subtitle: "Maximum Liability",
          text: "Our total liability to you for all claims arising from or related to these terms or our services shall not exceed the amount you paid us in the 12 months preceding the claim."
        }
      ]
    },
    {
      icon: XCircle,
      title: "Termination",
      content: [
        {
          subtitle: "Termination by You",
          text: "You may terminate your account at any time by contacting our support team or using the account closure feature in your settings. Termination will be effective at the end of your current billing period."
        },
        {
          subtitle: "Termination by Us",
          text: "We may suspend or terminate your access to our services immediately, without prior notice, if you violate these terms, fail to pay fees, or engage in activities that could harm our services or other users."
        },
        {
          subtitle: "Effect of Termination",
          text: "Upon termination, your right to access and use our services will immediately cease. We will provide you with an opportunity to export your data within 30 days of termination, after which we may delete your data in accordance with our data retention policies."
        }
      ]
    },
    {
      icon: RefreshCw,
      title: "Subscription & Billing",
      content: [
        {
          subtitle: "Fees & Payment",
          text: "You agree to pay all fees associated with your subscription plan. Fees are billed in advance on a monthly or annual basis, depending on your selected plan. All payments are processed securely through our third-party payment processors."
        },
        {
          subtitle: "Automatic Renewal",
          text: "Your subscription will automatically renew at the end of each billing period unless you cancel before the renewal date. You authorize us to charge your payment method for renewal fees."
        },
        {
          subtitle: "Price Changes",
          text: "We may change our pricing with 30 days' notice. Price changes will take effect at the start of your next billing period. If you do not agree to the price change, you may cancel your subscription."
        },
        {
          subtitle: "Refunds",
          text: "Fees are generally non-refundable except as required by law or as explicitly stated in your subscription agreement. We may provide refunds on a case-by-case basis at our sole discretion."
        }
      ]
    }
  ];

  const lastUpdated = "January 15, 2024";

  return (
    <AppLayout>
      <div className="space-y-12 max-w-5xl mx-auto">
        {/* Header */}
        <div className="text-center space-y-4">
          <Badge className="bg-gradient-primary text-primary-foreground">
            <FileText className="w-4 h-4 mr-2" />
            Terms of Service
          </Badge>
          <h1 className="text-4xl md:text-6xl font-space font-bold">
            Terms of
            <span className="block gradient-text">Service</span>
          </h1>
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
            Please read these terms carefully before using our AI solutions and services.
            These terms constitute a legally binding agreement between you and AI Solutions.
          </p>
          <p className="text-sm text-muted-foreground">
            Last Updated: {lastUpdated}
          </p>
        </div>

        {/* Introduction */}
        <Card className="glass-surface border-border/50">
          <CardContent className="p-8">
            <div className="flex items-start gap-4">
              <div className="w-12 h-12 bg-gradient-primary rounded-lg flex items-center justify-center flex-shrink-0">
                <Scale className="h-6 w-6 text-primary-foreground" />
              </div>
              <div className="space-y-3">
                <h2 className="text-2xl font-semibold">Legal Agreement</h2>
                <p className="text-muted-foreground leading-relaxed">
                  These Terms of Service ("Terms") govern your access to and use of AI Solutions'
                  artificial intelligence solutions, software, and services (collectively, the "Services").
                  This agreement is between you (either an individual or the entity you represent) and
                  AI Solutions Ltd.
                </p>
                <p className="text-muted-foreground leading-relaxed">
                  By clicking "I Accept," signing up for an account, or using our Services, you acknowledge
                  that you have read, understood, and agree to be bound by these Terms and our Privacy Policy.
                  If you are accepting on behalf of an organization, you represent that you have the authority
                  to bind that organization to these Terms.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Main Sections */}
        <div className="space-y-8">
          {sections.map((section, index) => (
            <Card key={index} className="hover-lift glass-surface border-border/50">
              <CardContent className="p-8">
                <div className="flex items-center gap-4 mb-6">
                  <div className="w-14 h-14 bg-gradient-primary rounded-xl flex items-center justify-center">
                    <section.icon className="h-7 w-7 text-primary-foreground" />
                  </div>
                  <h2 className="text-2xl font-space font-bold">{section.title}</h2>
                </div>
                <div className="space-y-6 ml-18">
                  {section.content.map((item, idx) => (
                    <div key={idx} className="space-y-2">
                      <h3 className="text-lg font-semibold text-primary">{item.subtitle}</h3>
                      <p className="text-muted-foreground leading-relaxed">{item.text}</p>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* Additional Legal Provisions */}
        <Card className="glass-surface border-border/50">
          <CardContent className="p-8">
            <h2 className="text-2xl font-semibold mb-6">Additional Provisions</h2>
            <div className="space-y-4 text-muted-foreground">
              <div>
                <h3 className="font-semibold text-foreground mb-2">Governing Law</h3>
                <p className="leading-relaxed">
                  These Terms shall be governed by and construed in accordance with the laws of England
                  and Wales, without regard to its conflict of law provisions. Any disputes arising from
                  these Terms shall be subject to the exclusive jurisdiction of the courts of England and Wales.
                </p>
              </div>
              <div>
                <h3 className="font-semibold text-foreground mb-2">Dispute Resolution</h3>
                <p className="leading-relaxed">
                  For any dispute arising from these Terms, you agree to first contact us to seek informal
                  resolution. If we cannot resolve the dispute informally, either party may pursue binding
                  arbitration or litigation in accordance with the governing law provisions.
                </p>
              </div>
              <div>
                <h3 className="font-semibold text-foreground mb-2">Severability</h3>
                <p className="leading-relaxed">
                  If any provision of these Terms is found to be unenforceable or invalid, that provision
                  will be limited or eliminated to the minimum extent necessary so that these Terms will
                  otherwise remain in full force and effect.
                </p>
              </div>
              <div>
                <h3 className="font-semibold text-foreground mb-2">Entire Agreement</h3>
                <p className="leading-relaxed">
                  These Terms, together with our Privacy Policy and any other policies referenced herein,
                  constitute the entire agreement between you and AI Solutions regarding your use of our
                  Services and supersede all prior agreements and understandings.
                </p>
              </div>
              <div>
                <h3 className="font-semibold text-foreground mb-2">Contact Information</h3>
                <p className="leading-relaxed">
                  For questions about these Terms, please contact us at legal@aisolutions.com or
                  AI Solutions Ltd., Sunderland, United Kingdom.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Acknowledgment Box */}
        <Card className="glass-surface border-primary/20 bg-primary/5">
          <CardContent className="p-6">
            <p className="text-sm text-muted-foreground leading-relaxed">
              <strong className="text-foreground">Acknowledgment:</strong> By using AI Solutions'
              services, you acknowledge that you have read and understood these Terms of Service
              and agree to be bound by them. If you do not agree to these Terms, you must not use
              our services.
            </p>
          </CardContent>
        </Card>
      </div>
    </AppLayout>
  );
};

export default Terms;
